# Generated by Django 2.0.1 on 2020-09-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureitem',
            name='resource',
            field=models.FilePathField(blank=True, verbose_name='文件夹位置'),
        ),
    ]
