# Generated by Django 2.0.1 on 2020-09-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200910_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureitem',
            name='resource',
            field=models.CharField(blank=True, max_length=100, verbose_name='文件夹位置'),
        ),
    ]
