# Generated by Django 2.0.1 on 2020-09-10 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200910_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureitem',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='pictureitem',
            name='file_name',
            field=models.CharField(max_length=100, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='pictureitem',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
