# Generated by Django 2.0.1 on 2020-09-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200910_1120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PictureItem',
            new_name='FolderItem',
        ),
    ]
