# Generated by Django 2.0.1 on 2020-09-10 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200910_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='文件名')),
                ('resource', models.CharField(blank=True, max_length=255, verbose_name='文件夹位置')),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='添加时间')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '图片媒体文件',
                'verbose_name_plural': '图片媒体文件',
            },
        ),
    ]
