# Generated by Django 2.0.1 on 2020-09-10 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_picitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='picitem',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FolderItemFK', to='app.FolderItem', verbose_name='目录'),
        ),
    ]
