# Generated by Django 2.0.1 on 2020-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_picitem_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='picitem',
            name='type',
            field=models.CharField(max_length=100, null=True, verbose_name='格式'),
        ),
    ]
