# Generated by Django 2.1.7 on 2020-09-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_picitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='picitem',
            name='res_header',
            field=models.CharField(max_length=100, null=True, verbose_name='响应头'),
        ),
    ]
