# Generated by Django 2.2.1 on 2020-09-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_picitem_res_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picitem',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FolderItemFK', to='app.FolderItem', verbose_name='目录'),
        ),
    ]
