# Generated by Django 2.1.7 on 2020-09-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200911_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='picitem',
            name='status',
            field=models.CharField(blank=True, choices=[('E', '正常'), ('F', '无效')], default='E', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='folderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('E', '正常'), ('F', '无效')], default='E', max_length=10, verbose_name='状态'),
        ),
    ]
