# Generated by Django 2.1.7 on 2020-09-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200911_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderitem',
            name='type',
            field=models.CharField(blank=True, choices=[('P', '图片'), ('V', '视频')], default='P', max_length=10, verbose_name='媒体类型'),
        ),
    ]
