# Generated by Django 2.2.1 on 2020-09-13 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_folderitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('folder_item_id', models.CharField(max_length=100, verbose_name='访问文件夹')),
                ('status', models.CharField(blank=True, choices=[('E', '正常'), ('F', '无效')], default='E', max_length=10, verbose_name='状态')),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='添加时间')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户访问权限管理',
                'verbose_name_plural': '用户访问权限管理',
            },
        ),
        migrations.AlterModelOptions(
            name='folderitem',
            options={'verbose_name': '文件夹管理', 'verbose_name_plural': '文件夹管理'},
        ),
        migrations.AlterModelOptions(
            name='picitem',
            options={'verbose_name': '媒体文件管理', 'verbose_name_plural': '媒体文件管理'},
        ),
    ]
