# Generated by Django 2.2.1 on 2020-09-13 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_auto_20200913_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='username',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userTokenFK', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
