# Generated by Django 2.1.7 on 2021-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200913_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='picitem',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件网络路径'),
        ),
        migrations.AlterField(
            model_name='picitem',
            name='resource',
            field=models.CharField(blank=True, max_length=255, verbose_name='文件真实路径'),
        ),
    ]
