# Generated by Django 2.2.1 on 2021-01-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210108_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='picitem',
            name='img_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='视频封面'),
        ),
    ]
